[package]
name = "gcp-lookup"
version = "0.1.0"
authors = ["Kenec <nnamani.kenechukwu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]